### ISSUE TITLE
NameError: name 'E3DC' is not defined

### ISSUE THREAD

**Issue by jhubig** [MatrixCrawler/python-e3dc-module#1]
Hello,

I have just installed your library on my machine (Raspberry 3B - Python 3.5.3):

```shell

sudo pip3 install git+https://github.com/MatrixCrawler/python-e3dc-module.git
Collecting git+https://github.com/MatrixCrawler/python-e3dc-module.git
  Cloning https://github.com/MatrixCrawler/python-e3dc-module.git to /tmp/pip-4p_ahb5j-build
Requirement already satisfied: py3rijndael in /usr/local/lib/python3.5/dist-packages (from e3dc==0.0.5)
Installing collected packages: e3dc
  Running setup.py install for e3dc ... done
Successfully installed e3dc-0.0.5
```

![image](https://user-images.githubusercontent.com/7255837/99915055-94d2eb00-2d01-11eb-866b-b15ace89419d.png)

Unfortunately already the 10th line of the code gives me troubles 😀 . Maybe I'm just blind to see it. Would be great if you could have a quick look.

```shell
Traceback (most recent call last):
  File ".homebridge/Cmd4Scripts/e3dc_connect.py", line 10, in <module>
    e3dc = E3DC(USERNAME, PASS, TCP_IP, KEY)
NameError: name 'E3DC' is not defined
```

```python
#!/usr/bin/python3
from e3dc import *

TCP_IP = 'xxx'
USERNAME = 'xxx'
PASS = 'xxx'
KEY = 'xxx'
SERIALNUMBER = 'xxx'

e3dc = E3DC(USERNAME, PASS, TCP_IP, KEY)
# request the current power that is produced by the pv system
response = e3dc.send_request(RSCPTag.EMS_REQ_POWER_PV)
print("Current power "+str(response.data))

```

_For info: Before I have tried your package, I also tried the one from https://github.com/fsantini/python-e3dc. But I uninstalled it before installing yours._

**Comment by MatrixCrawler** [comment]
Did you try the following imports?

```
from e3dc._rscp_exceptions import RSCPCommunicationError  
from e3dc.e3dc import E3DC  
from e3dc.rscp_tag import RSCPTag
```

I am not sure if the `from e3dc import *` works correctly in that case

**Comment by jhubig** [comment]
Currently I'm using the plugin from fsantini again. So currently no need to use this plugin - Sorry :( . In case I will try again I might come back to you but I would close the issue for now.

Thanks for your help.

Cheers,
Johannes
